Band.create(name: "Middle Blue", genre: "jazz", popularity: "small")
Band.create(name: "The Meters", genre: "funk", popularity: "big")
Band.create(name: "Rihanna", genre: "pop", popularity: "big")
Band.create(name: "John Coltrane", genre: "jazz", popularity: "big")
Band.create(name: "Alice Coltrane", genre: "jazz", popularity: "big")
Band.create(name: "Frank Ocean", genre: "pop", popularity: "big")
Band.create(name: "Jeremy Danneman", genre: "jazz", popularity: "small")
Band.create(name: "Kendrick Lamar", genre: "hip-hop", popularity: "big")
Band.create(name: "Jounce", genre: "rock", popularity: "small")
Band.create(name: "Charles Mingus", genre: "jazz", popularity: "big")


City.create(name: "Brooklyn", state: "New York")
City.create(name: "New York", state: "New York")
City.create(name: "Burlington", state: "Vermont")
City.create(name: "Northampton", state: "Massachusetts")
City.create(name: "Boston", state: "Massachusetts")
City.create(name: "Beacon", state: "New York")
City.create(name: "Chicago", state: "Illinois")
City.create(name: "Philadelphia", state: "Pennsylvania")
City.create(name: "New Orleans", state: "Louisiana")
City.create(name: "Amherst", state: "Massachusetts")


Show.create(start_time: Time.parse("8:00 PM"), end_time: Time.parse("10:00 pm"), venue_id: 1, band_id: 1)
Show.create(start_time: Time.parse("9:00 PM"), end_time: Time.parse("11:00 pm"), venue_id: 2, band_id: 2)
Show.create(start_time: Time.parse("7:00 PM"), end_time: Time.parse("8:00 pm"), venue_id: 3, band_id: 3)
Show.create(start_time: Time.parse("7:00 PM"), end_time: Time.parse("9:00 pm"), venue_id: 4, band_id: 4)
Show.create(start_time: Time.parse("8:00 PM"), end_time: Time.parse("10:00 pm"), venue_id: 5, band_id: 5)
Show.create(start_time: Time.parse("7:00 PM"), end_time: Time.parse("11:00 pm"), venue_id: 6, band_id: 6)
Show.create(start_time: Time.parse("8:00 PM"), end_time: Time.parse("9:00 pm"), venue_id: 7, band_id: 7)
Show.create(start_time: Time.parse("9:00 PM"), end_time: Time.parse("10:00 pm"), venue_id: 8, band_id: 8)
Show.create(start_time: Time.parse("10:00 PM"), end_time: Time.parse("11:00 pm"), venue_id: 9, band_id: 9)
Show.create(start_time: Time.parse("9:00 PM"), end_time: Time.parse("10:00 pm"), venue_id: 10, band_id: 10)


Venue.create(name: "Troost", address: "1011 Manhattan Avenue", neighborhood: "Greenpoint", size: "small", city_id: 1) 
Venue.create(name: "Bowery Ballroom", address: "6 Delancey Street", neighborhood: "Lower East Side", size: "big", city_id: 2) 
Venue.create(name: "Higher Ground", address: "1214 Williston Road", neighborhood: "South Burlington", size: "big", city_id: 3) 
Venue.create(name: "Calvin Theatre", address: "19 King Street", neighborhood: "Downtown", size: "big", city_id: 4) 
Venue.create(name: "Lizard Lounge", address: "1667 Massachusetts Avenue", neighborhood: "Cambridge", size: "big", city_id: 5) 
Venue.create(name: "Quinn's", address: "330 Main Street", neighborhood: "Downtown", size: "big", city_id: 6) 
Venue.create(name: "The Green Mill", address: "4802 North Broadway", neighborhood: "Uptown", size: "small", city_id: 7) 
Venue.create(name: "Franklin Music Hall", address: "421 North 7th St", neighborhood: "Callowhill", size: "big", city_id: 8) 
Venue.create(name: "Maple Leaf", address: "8316 Oak Street", neighborhood: "Carrollton", size: "small", city_id: 9) 
Venue.create(name: "UMass Fine Arts Center", address: "151 Presidents Drive", neighborhood: "On Campus", size: "big", city_id: 10) 
